// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymkSBj13TASxe7EftcYup2h1dCG1V8IU',
    appId: '1:537573740298:web:0a8b8fa7c72f2d405f34f3',
    messagingSenderId: '537573740298',
    projectId: 'baberqueue',
    authDomain: 'baberqueue.firebaseapp.com',
    storageBucket: 'baberqueue.firebasestorage.app',
    measurementId: 'G-6BZWVN3N2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wfofJ_u4hOZrB26Wbf2ixg9-s_z3z7Q',
    appId: '1:537573740298:android:c29386c46659a3e25f34f3',
    messagingSenderId: '537573740298',
    projectId: 'baberqueue',
    storageBucket: 'baberqueue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7Xu5XdRt5XQA5tFBCcOGnnCTrELqQxY',
    appId: '1:537573740298:ios:aa28aa9853ff2e715f34f3',
    messagingSenderId: '537573740298',
    projectId: 'baberqueue',
    storageBucket: 'baberqueue.firebasestorage.app',
    iosBundleId: 'com.example.barberQueue',
  );
}
